### ISSUE TITLE
Extra quote resulting in error in Macro Tutorial

### ISSUE THREAD

**Issue by kisaragi-hiu** [mullikine/blog#1]
In the last paragraph of [Didactic emacs-lisp macro example (ie. a tutorial)](https://mullikine.github.io/posts/macro-tutorial/), this code example

```elisp
(defmacro show-map (m)
  (let ((mstring (concat "\\{" (symbol-name m) "}")))
    (new-buffer-from-string (substitute-command-keys mstring))))
(show-map 'helm-map)
```

errors out, because `helm-map` has an extra quote, appearing as `(quote helm-map)` (a list of two symbols) in `show-map`'s body.

**Comment by mullikine** [comment]
Thank you so much! I have fixed it. ♡
